apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: ollama
spec:
  type: conversation.openai
  version: v1
  metadata:
  - name: key
    value: 'ollama'
  - name: model
    value: gpt-oss:20b
  - name: endpoint
    value: 'http://localhost:11434/v1' # ollama endpoint https://ollama.com/blog/openai-compatibility
